### ISSUE TITLE
xhr.js:175 POST http://localhost:3000/api/articles/11/comments 500 (Internal Server Error)

### ISSUE THREAD

**Issue by hirooutdoor** [hirooutdoor/instalikeapp#50]
- [ ] can't comment on the articles
xhr.js:175 POST http://localhost:3000/api/articles/11/comments 500 (Internal Server Error)

**Comment by hirooutdoor** [comment]
```
active_model_serializers] Rendered CommentSerializer with ActiveModelSerializers::Adapter::Attributes (3.75ms)
Completed 500 Internal Server Error in 54ms (ActiveRecord: 25.3ms | Allocations: 14437)



NoMethodError (undefined method `attached?' for "Ellipse.png":String):

app/serializers/user_serializer.rb:29:in `comment_avatar_image'
app/controllers/api/comments_controller.rb:17:in `create'
```
