### ISSUE TITLE
NoMethodError in ProfilesController#update undefined method `call' for #<ActionController::Parameters:0x000

### ISSUE THREAD

**Issue by hirooutdoor** [hirooutdoor/instalikeapp#53]
プロフィールの画像を変更しようとした際に起こるエラー

**Comment by hirooutdoor** [comment]
https://stackoverflow.com/questions/25770268/unpermitted-parameters-profile-nestedattributes-rails-4

**Comment by hirooutdoor** [comment]
user.rbとprofiles_controllerの繋ぎがうまく行っていない可能性

**Comment by hirooutdoor** [comment]
### 気になる処理①


```
Unpermitted parameters: :_method, :authenticity_token, :profile, :commit
  Rendering profiles/show.html.haml within layouts/application
  ActiveStorage::Attachment Load (1.1ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 9], ["record_type", "Profile"], ["name", "avatar"], ["LIMIT", 1]]
  ↳ app/models/user.rb:57:in `avatar_image'
[Webpacker] Everything's up-to-date. Nothing to do
```

**Comment by hirooutdoor** [comment]
### 気になる処理②

commitはfalseになっていない
```
Processing by ProfilesController#update as HTML
  ↳ app/models/user.rb:53:in `prepare_profile'
Unpermitted parameter: :profile
  Rendering profiles/show.html.haml within layouts/application
  Parameters: {"authenticity_token"=>"akt1WeXMEvndmjxdaFrXloq3/1Y1fViobFQcjDkHfwGbcqIIicfUOdJYDk5+OZetpBb++iiqmaxc/76w+L3QXA==", "profile"=>{"avatar"=>#<ActionDispatch::Http::UploadedFile:0x00007fa0461e71a0 @tempfile=#<Tempfile:/var/folders/dr/3m5y74655xl78vbq3m72t49w0000gn/T/RackMultipart20210112-19615-1dwvca1.jpg>, @original_filename="N08-fKsO.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"profile[avatar]\"; filename=\"N08-fKsO.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "commit"=>""}
```

**Comment by hirooutdoor** [comment]
また明日やろう

**Comment by hirooutdoor** [comment]
### 状況

元々アバター画像を変更しようとすると
なぜかエラーが多発していた。

そして原因はおそらくProfilecコントローラーのupdateのprivateメソッドがおかしかった


```
  private
    def profile_params
      params.require(:profile).permit(:avatar)
    end
```
これができないので

```
  private
    def profile_params
      params.permit(:avatar)
    end

```
このように記述したところ
先ほどのようなエラーが出るようになった・


アバター画像の変更は可能になったが、一度きりしかできない

JSのエラー内容
```
profile.js:37 Uncaught TypeError: Cannot read property 'accountId' of undefined
    at HTMLDocument.<anonymous>
```

**Comment by hirooutdoor** [comment]
https://app.slack.com/client/T013BGXQ8FQ/C0156CCTBL1/thread/C0156CCTBL1-1610249063.477100

デイトラ の質問で同じようなエラーに引っかかっている人がいた！
！
